name: ACLLiveEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.5=py311hfdbb021_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311h9ecbd09_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.11.9=hb806964_0_cpython
  - python_abi=3.11=5_cp311
  - pyzmq=26.2.0=py311h7deb3e3_2
  - readline=8.2=h8228510_1
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py311h9ecbd09_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.1=pyhd8ed1ab_0
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.3.0
      - cloudpickle==3.1.1
      - colour==0.1.5
      - contourpy==1.3.0
      - cucim-cu12==25.10.0
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dask==2025.10.0
      - dtreeviz==2.2.2
      - et-xmlfile==1.1.0
      - fastrlock==0.8.2
      - filelock==3.16.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - h5py==3.11.0
      - hdbscan==0.8.38.post1
      - idna==3.8
      - imageio==2.35.1
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==3.5.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - locket==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - namex==0.0.8
      - nd2==0.10.3
      - networkx==3.3
      - nptyping==2.5.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - ome-types==0.6.2
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.2
      - partd==1.4.2
      - pillow==10.4.0
      - pluggy==1.5.0
      - protobuf==4.25.4
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pynrrd==1.0.0
      - pyparsing==3.1.4
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - resource-backed-dask-array==0.1.0
      - rich==13.8.0
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - simpleitk==2.4.0
      - sympy==1.13.2
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorrt==10.4.0
      - tensorrt-cu12==10.4.0
      - tensorrt-cu12-bindings==10.4.0
      - tensorrt-cu12-libs==10.4.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - toolz==1.1.0
      - torch==2.4.1
      - torch-tb-profiler==0.4.3
      - torch-vision==0.1.6.dev0
      - tqdm==4.66.5
      - triton==3.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - xsdata==25.7
prefix: /home/brian/.conda/envs/ACLLiveEnv
